# Generated by Django 4.2.4 on 2023-09-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_pocket_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pocket',
        ),
    ]
